### ISSUE TITLE
Setup testing for bebop@anl

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psi-j-python#137]
Setup automated testing on bebop

**Comment by wilke** [comment]
Created cronjob. Using conda environment.

**Comment by wilke** [comment]
Got error:
```
Unrecognized command line option: --with-conda.
Usage: ./psij-ci-run [--help] [--with-conda <conda_env_name>]
            [--with-venv <venv_name>] [--repeat]
    --help          Displays this message
    --with-conda    Specifies a conda environment to activate before running
                    the tests
    --with-venv     Specifies a virtualenv environment to load before running
                    the tests
    --repeat        If specified, run tests every 24 hours in a loop.
```

**Comment by hategan** [comment]
I don't think --with-conda is used any more. It should be removed from the help message. If you need to load a conda environment, put the relevant commands in psij-ci-load, which gets sourced by psij-ci-run.

**Comment by wilke** [comment]
Stating the obvious, cron is running in a limited user environment.
Adding conda environment variables to psij-ci-load and conda activate seems to solve the issue.
