### ISSUE TITLE
Properly deal with errors in the status loop of batch schedulers

### ISSUE THREAD

**Issue by hategan** [ExaWorks/psi-j-python#144]
If `get_status_command` throws an exception, such as `NotImplementedError`, the `BatchSchedulerJobExecutor` status loop exits and then nothing gets updated any more. This is quite obviously wrong. Exceptions from each job status query should be isolated and reported properly.

**Comment by andre-merzky** [comment]
I may be totally missing something, but it looks like this is already implemented?

`get_status_command` is called [here](https://github.com/ExaWorks/psi-j-python/blob/main/src/psij/executors/batch/batch_scheduler_executor.py#L560): 
```py
        try:
            out = self.executor._run_command(self.executor.get_status_command(jobs_copy.keys()))
        except subprocess.CalledProcessError as ex:
            out = ex.output
            exit_code = ex.returncode
        else:
            exit_code = 0
            self._poll_error_count = 0
```
Any exception is stored on failure.  The `_poll_error_count` is evaluated in `_handle_poll_error` which will get always triggered if the above call returns a non-zero exit code as the `parse_status_output` call will raise an exception in that case (see [line 572](https://github.com/ExaWorks/psi-j-python/blob/main/src/psij/executors/batch/batch_scheduler_executor.py#L569)
```py
        try:
            status_map = self.executor.parse_status_output(exit_code, out)
        except Exception as ex:
            self._handle_poll_error(True,
                                    ex,
                                    f'Failed to poll for job status: {traceback.format_exc()}')
            return
```

`_handle_poll_error` will accept an error up to `self.config.queue_polling_error_threshold` times and only then move all jobs into `FAILED` state.

What am I missing?

**Comment by hategan** [comment]
@andre-merzky: any exceptions other than CalledProcessError thrown by get_status_command or _run_command will cause the main polling loop to exit.

**Comment by andre-merzky** [comment]
Me taking this ticket was an attempt to support you guys, but yet, here I am, not getting it and creating noise... :-/

`get_status_command` is not a remote operation and assembles the command string from the job IDs.  As such I would consider it a pure function.  If that fails on certain parameters then it should fail on a repeated call with the same parameters again, so I don't think it should be retried, and any exception should fall through.

`_run_command` will only raise one exception type, the `subprocess.CalledProcessError`.  I don't see any other exception documented in `subprocess.run`, nor see I any possible exception from the code in `_run_command` which would not raise again on a retry (like, dunno, out of memory or whatever).

I mean, no problem to do a blanket except instead if that's wanted?

Again, sorry for the noise - but could someone venture some specifics or even a reproducer on what specifically is broken here?

**Comment by hategan** [comment]
> Me taking this ticket was an attempt to support you guys, but yet, here I am, not getting it and creating noise... :-/

Don't be silly. This is noise: "dBJ48abhf3qHf049gSHbF8vhdFmgMCFTT5XIkpzK". I think we're both getting a better understanding of the system and problem.

> `get_status_command` [...] If that fails on certain parameters then it should fail on a repeated call with the same parameters again, so I don't think it should be retried, and any exception should fall through.

Yes. The question is whether this should quietly freeze the entire system. 

The end result of the polling loop exiting is that all jobs that were submitted will indefinitely remain in their current state. Ideally, one would fail the job that triggered the problem with some equivalent of an internal error and continue to normally process jobs that do not have a problem.

To give some context, in implementing the PBS executor, Ben did manage to have get_status_command raise an exception, which resulted in things quietly freezing. It's rare, it shouldn't happen in production code (although we cannot offer guarantees -- even less so with user-contributed executors), but if it does, it would be nice if it was handled more gracefully.

**Comment by andre-merzky** [comment]
Thanks @hategan, that clearified things.
