### ISSUE TITLE
Missing dev requirements

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/psi-j-python#17]
`pytest`, `flake8`, `mypy` are missing from the `requirements-dev.txt`.  I think they should be added.

Is there a particular set of versions we should pin them to? Or just always go with the latest?  If we tie their passing to the CI, we've had issues in Flux where CI will start failing on a random PR due to a version bump by one of the static analysis tools.

**Comment by hategan** [comment]
> `pytest`, `flake8`, `mypy` are missing from the `requirements-dev.txt`

Are they? 

https://github.com/ExaWorks/psi-j-python/blob/main/requirements-dev.txt

**Comment by SteVwonder** [comment]
Ah. Sorry for the noise.  They weren't on #11, and didn't realize that was out-of-date w.r.t. master/main. Thanks!

**Comment by hategan** [comment]
I think the issue of particular versions of tools merits some attention though. If we want reproducibility, pinning may be wise. On the other hand, we may want to capture evolutionary steps in the standards against which the code is compared, so using the latest versions of tools may make more sense from that perspective. We can go with latest version for now, but may want to reconsider this question in the future.
