### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/psi-j-python#20]
As we discussed today on the call, we should try and converge on a coding style.

There are a few popular options that I found:

- [black](https://github.com/psf/black)
- [pycodestyle](https://github.com/pycqa/pycodestyle) (formerly pep8)
- [yapf](https://github.com/google/yapf)

----

My personal preference is for black.  We use it on Flux, Spack, and a few other LLNL projects.  It is actually the formatter/style recommended internally at Livermore Computing.  Everyone has a different qualm or nitpick with the style that it enforces, but most people I talk to are fine with it overall.  The major benefit with it is that it has no configuration, so you never spend any time fighting with people over how things should be; they are just what they are.  Another minor benefit is that black makes code review easier my optimizing for smaller diffs.  Relevant excerpt from their README:

> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.  Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead. Black makes code review faster by producing the smallest diffs possible.

Also relevant, Ian Lee is an LC employee that used to be a major contributor to pycodestyle (# 2 in LOC), but AFAIK he now recommends people use black.

All that said, I'd be happy to use the other formatting tools, but I have no interest in configuring them or iterating on the format style.  So if we go with pycodestyle or yapf, I will just use whatever config is decided upon by others.

**Comment by hategan** [comment]
The code is already pep8 compliant and this is automatically checked by `make checks`, which uses `flake8`. Pycodestyle is a tool similar to flake8, in the sense that it only checks against pep8 compliance. Black and yapf are formatters, the latter also conforming to pep8.

On the existing code, `yapf` may re-flow some lines, which were manually split because of line length restrictions in a way that was meant to maximize readability. For example:

```
def f(self,                           |
      long_param_1, long_param_2)     |
```

instead of 
```
def f(self, long_param_1,             |
      long_param_2)                   |
```

So the important question here is not to choose a code style, but whether there is sufficient justification to switch from standard pep8 (what yapf would generate) to black and whether black is something that potential contributors/maintainers would find easier to deal with than plain pep8.

**Comment by SteVwonder** [comment]
> Pycodestyle is a tool similar to flake8, in the sense that it only checks against pep8 compliance. Black and yapf are formatters, the latter also conforming to pep8.

Good call out on the distinction.  I also failed to [`autopep8`](https://github.com/hhatto/autopep8), which looks to be a formatter that automatically applies the changes suggested by pycodestyle.

> and whether black is something that potential contributors/maintainers would find easier to deal with than plain pep8.

I would say I think contributors will find a formatter easier to deal with than just a linter/compliance checker.  Having the "right" stye applied automatically is much nicer than having a tool tell you which manual changes to make.

> whether there is sufficient justification to switch from standard pep8 (what yapf would generate) to black

As far as black's format versus pep8, I don't care all that much.  Either one is fine with me.  As long as we don't spend endless hours iterating on `yapf`'s config (I'm assuming the default config works well, or someone has one we can copy?), then that's fine with me.

**Comment by hategan** [comment]
> > and whether black is something that potential contributors/maintainers would find easier to deal with than plain pep8.
> 
> I would say I think contributors will find a formatter easier to deal with than just a linter/compliance checker. Having the "right" stye applied automatically is much nicer than having a tool tell you which manual changes to make.

"Deal with" not necessarily in the sense of not having to do anything, but in the sense of working with the formatted code. I don't think we have evidence either way, but, given that black is the newcomer, I'd wait until we get such evidence in the way of traction among python projects. I can probably run a test on my local python libs, but I suspect few if any use black.>

> As far as black's format versus pep8, I don't care all that much. Either one is fine with me. As long as we don't spend endless hours iterating on yapf's config (I'm assuming the default config works well, or someone has one we can copy?), then that's fine with me.

I think we may want to split this discussion into two:
1. whether we automatically use a formatter as opposed to manually invoking it when wanted
2. what style should we conform to, if any, whether automatically applied or not (as in (1))

**Comment by SteVwonder** [comment]
> "Deal with" not necessarily in the sense of not having to do anything, but in the sense of working with the formatted code.

Gotcha.  In that case, I think "working with" here includes reading, writing, and reviewing it.  If you use a formatter, then I think the `writing` piece is less important.   I also think the amount of time a contributor has to spend complying with the style guide also matters (and again, a formatter reduces this significantly).

> but I suspect few if any use black

It has 20k stars and 53k "used by" on Github: https://github.com/psf/black.  Yapf has 11.7K stars and 18.6K "used by" on Github: https://github.com/google/yapf.  Autopep8 has 3.8K stars and 73k "used by" on Github: https://github.com/hhatto/autopep8  I think that shows that black is pretty popular and has a good amount of traction in the overall community (in terms of raw numbers; I'm not sure how many of the "big" python projects use it).

> I think we may want to split this discussion into two

I sort of agree, but ultimately these two things are connected.  If we have a way to automatically apply formatting, I (personally) care way less about which code style is used (as long as its relatively popular).  But I'm happy to break them apart and start with item 1 as proposed:

> whether we automatically use a formatter as opposed to manually invoking it when wanted

I would argue heavily in favor of having a formatter (i.e., it doesn't just check my code is in compliance with the style but actually has an option to bring the code into compliance without my intervention).  Having an automatic formatter greatly improves development/contribution time since you don't have to worry about manually adding newlines, tabs, spaces, etc in all the various places your linter/style checker tells you to.  It can just do it for you.  It also means that if you are a new contributor used to a different code style, you don't have to labor over learning a new one; the tool can handle that complexity for you.   AFAICT, `flake8` does not do this automatically, so if we stick with the PEP8 style, I would argue we should either find a tool that can automatically bring code into `flake8` compliance, or switch to a different style checker/formatter.

As to whether or not we have it automatically applied as part of our CI, I don't care too much.  I think having the ability for the contributor to run the formatter themselves is probably sufficient.  And then we just run the style check as part of the CI to ensure that no incorrectly formatted code is merged (and the contributor has to apply the style fixes themselves and re-push to the PR).  That way we ensure code style consistency without creating issues with users PRs due to tools force-pushing etc.

Thoughts?

> what style should we conform to, if any, whether automatically applied or not (as in (1))

I think we should certainly strive to have an agreed upon code style.  That eliminates any nitpicks and discussions in individual PRs about how particular code is formatted, and the PR process can be focused on correctness/maintainability/etc.

As to whether it is PEP8, PEP8-based yapf style, a custom yapf-enforced style, black, etc, I don't particularly care as long as we have a formatter than can apply the format/style automatically.  I think they are all pretty readable. I think we should  avoid making too custom of a style and stick generally to the most popular styles - to both avoid spending all of our time tweaking code style configs as well as to maximize the probability a contributor is familiar with the style.

Are there any other popular styles in particular we should be considering besides PEP8 and black?

**Comment by jameshcorbett** [comment]
To throw in my opinion: I'm a strong supporter of having an automatic formatter. I also think Black makes it easy: `pip install black; black path/to/package`. I don't think Black's format is better than `pycodestyle` or any other formatter, I just think it is nice to have one and to make using it easy. I hate thinking about line length and whether my parentheses are indented properly.

And yeah, when someone comes to the project, it's a lot easier to say "you need to run ..." instead of "this line here is wrong and so is this one here and that one there..."

As for popularity, [pandas uses black](https://github.com/pandas-dev/pandas/blob/master/doc/source/development/contributing.rst#autofixing-formatting-errors). A couple of other "big" Python projects that I've heard of [use it](https://github.com/psf/black#used-by).

**Comment by hategan** [comment]
> I'm a strong supporter of having an automatic formatter. [...] I hate thinking about line length and whether my parentheses are indented properly.

I think we all agree on that.

I'm probably a bit biased in this discussion, since I tend to use an IDE, which already comes with a non-intrusive auto-formatter (e.g., when you press enter, it magically indents correctly depending on context).

> As one example, I am working on my first C contribution to flux-core right now. [...] But knowing that I can just clang-format my way to some sort of neatness will help me reduce the number of new things I have to learn about and pay attention to.

That's actually a very good point. Having a tool that can easily be invoked by a contributor can lower the barrier for people to contribute code. And an IDE is too heavy of a requirement to impose on users.

**Comment by SteVwonder** [comment]
On the ☎️ call, we decided to try a pep8 automatic formatter - specifically `autopep8` - to see if it makes a minimal amount of churn on the current codebase, which would be a strong signal that we wouldn't have to fight it going forward.
