### ISSUE TITLE
Docstring Format

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/psi-j-python#21]
As discussed on the call today, we agreed on using Sphinx to generate our documentation from docstrings, but we need to decide/agree on a docstring format.  The three most popular formats are [RestructuredText](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html), [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), and [Numpy-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy).

The latter two are supported in Sphinx via the [Napoleon extension](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html) (which actually now ships as a part of Sphinx proper).  The Napoleon documentation has a great overview of the situation: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html.  The tl;dr (too long didn't read) is: Napoleon pre-processes the google/numpy docstrings into the RestructuredText format before handing things over to sphinx for parsing and doc generation.  This means that all three formats can live together in the same codebase and even within the same docstring.  I'm not sure if google/numpy covers literally every feature of sphinx's docstrings, but if not, you can always fallback to ReST syntax for that particular feature/line.

-----

IMO, google and numpy style are way more legible (to me, the RestructuredText docstrings border on line noise sometimes with all the colons, poor grouping of type with description and poor separation of args, returns, exceptions, descriptions).  They are also much easier to remember and write than ReST.  IMO, the google format is easier to write than the numpy format since it uses tabs rather than `------`; so my vote is for the google style.  Ultimately, I would also be totally fine with the numpy format too.  Out of ease-of-use and legibility concerns, I vote against the ReST format/syntax.

**Comment by hategan** [comment]
I would like to ask that we don't involve personal preferences here, but, instead, find more objective things, suitable for the goal of making the code familiar to arbitrary coders.

One idea I thought of is to figure out what the packages installed on my machine use. Here are the statistics:

'''
/usr/local/lib/python3/dist-packages

None: 73
['reST']: 53
['Numpy']: 15
['Numpy', 'reST']": 13
['Google', 'Numpy', 'reST']: 8
['Google']: 6
['Google', 'reST']: 4
['Epytext']: 4
['Epytext', 'Google', 'Numpy']: 2
['Google', 'Numpy']: 2 
['Epytext', 'reST']: 2
['Epytext', 'Google', 'Numpy', 'reST']: 1

/usr/lib/python3/dist-packages
None: 61
['reST']: 26 
['Numpy']: 15
['Numpy', 'reST']: 7 
['Epytext', 'reST']: 4
['Epytext']: 4
['Google']: 2
['Google', 'Numpy']: 1
['Google', 'reST']: 1
['Google', 'Numpy', 'reST']: 1
['Epytext', 'Numpy']: 1
'''

There are some false positives in the Numpy area since '------' is used as a signature, which can occur in other cases. Also, yes, there are packages that mix things quite a bit and lots of packages that do not use any structure, just their own style of comments.

**Comment by hategan** [comment]
One thing that may be worth mentioning is that Sphinx can extract parameter types from type annotations and does not require separate type specifications in the docstrings, so, at least as far as this project is concerned (i.e., we require type annotations), the info in https://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html is not entirely accurate/applicable.

**Comment by SteVwonder** [comment]
> One idea I thought of is to figure out what the packages installed on my machine use. Here are the statistics

Thanks for running that.  For the packages on your system, it looks to me like reST is the most popular (~110), Numpy is used quite heavily as well (~65), and Google doesn't seem to be used that much.  I think that is a good argument for excluding Google as an option, but I think the Numpy format is popular enough to still be considered.

My (partially subjective) argument for not using the reST format is that it is too dense and poorly structured:

```
    :param client: A handle to the :class:`simpleble.SimpleBleClient` client
        object that detected the device
    :type client: class:`simpleble.SimpleBleClient`
    :param addr: Device MAC address, defaults to None
    :type addr: str, optional
    :param addrType: Device address type - one of ADDR_TYPE_PUBLIC or
        ADDR_TYPE_RANDOM, defaults to ADDR_TYPE_PUBLIC
    :type addrType: str, optional
    :param iface: Bluetooth interface number (0 = /dev/hci0) used for the
        connection, defaults to 0
    :type iface: int, optional
    :param data: A list of tuples (adtype, description, value) containing the
        AD type code, human-readable description and value for all available
        advertising data items, defaults to None
    :type data: list, optional
    :param rssi: Received Signal Strength Indication for the last received
        broadcast from the device. This is an integer value measured in dB,
        where 0 dB is the maximum (theoretical) signal strength, and more
        negative numbers indicate a weaker signal, defaults to 0
    :type rssi: int, optional
    :param connectable: `True` if the device supports connections, and `False`
        otherwise (typically used for advertising ‘beacons’).,
        defaults to `False`
    :type connectable: bool, optional
    :param updateCount: Integer count of the number of advertising packets
        received from the device so far, defaults to 0
    :type updateCount: int, optional
    :raises bluepy.btle.BTLEException.GATT_ERROR: If no inputs are specified
        or the requested characteristic was not found.
    :returns: True or False indicating success or failure of write operation, in the
        case that withResponce is True
    :rtype: bool
```

As you mention, we use python3 type annotations, which napoleon and sphinx can both parse, so it does look a bit better and more structured/organized when you pull the type tags out of the docstring:

```
    :param client: A handle to the :class:`simpleble.SimpleBleClient` client
        object that detected the device
    :param addr: Device MAC address, defaults to None
    :param addrType: Device address type - one of ADDR_TYPE_PUBLIC or
        ADDR_TYPE_RANDOM, defaults to ADDR_TYPE_PUBLIC
    :param iface: Bluetooth interface number (0 = /dev/hci0) used for the
        connection, defaults to 0
    :param data: A list of tuples (adtype, description, value) containing the
        AD type code, human-readable description and value for all available
        advertising data items, defaults to None
    :param rssi: Received Signal Strength Indication for the last received
        broadcast from the device. This is an integer value measured in dB,
        where 0 dB is the maximum (theoretical) signal strength, and more
        negative numbers indicate a weaker signal, defaults to 0
    :param connectable: `True` if the device supports connections, and `False`
        otherwise (typically used for advertising ‘beacons’).,
        defaults to `False`
    :param updateCount: Integer count of the number of advertising packets
        received from the device so far, defaults to 0
    :raises bluepy.btle.BTLEException.GATT_ERROR: If no inputs are specified
        or the requested characteristic was not found.
    :returns: True or False indicating success or failure of write operation, in the
        case that withResponce is True
```

With Numpy-style (and Google-style), there are enforced headers, which split up the arguments from the return, raised exceptions, notes, examples, etc.  That way you can easily visually distinguish those sections.  The header also removes the need for duplicating `:param`, which cuts down on the line noise and makes it easier to find the argument/parameter that you are looking for.  And a new line after the parameter name separates the name from the description, distinguishing the two pieces of text.  As a standalone piece of text, the Numpy-style is much more legible to me:

```
Parameters
-----------
client
    A handle to the :class:`simpleble.SimpleBleClient` client
    object that detected the device
addr
    Device MAC address, defaults to None
addrType
    Device address type - one of ADDR_TYPE_PUBLIC or
    ADDR_TYPE_RANDOM, defaults to ADDR_TYPE_PUBLIC
iface
    Bluetooth interface number (0 = /dev/hci0) used for the
    connection, defaults to 0
data
    A list of tuples (adtype, description, value) containing the
    AD type code, human-readable description and value for all available
    advertising data items, defaults to None
rssi
    Received Signal Strength Indication for the last received
    broadcast from the device. This is an integer value measured in dB,
    where 0 dB is the maximum (theoretical) signal strength, and more
    negative numbers indicate a weaker signal, defaults to 0
connectable
    `True` if the device supports connections, and `False`
    otherwise (typically used for advertising ‘beacons’).,
    defaults to `False`
updateCount
    Integer count of the number of advertising packets
    received from the device so far, defaults to 0

Raises
-------
bluepy.btle.BTLEException.GATT_ERROR
    If no inputs are specified or the requested characteristic was not found.

Returns
--------
bool
    True or False indicating success or failure of write operation, in the
    case that withResponce is True
```

The numpy format also makes it easy to include inline `notes` and `examples` uses section headers consistent with the section headers for parameters, return, and raises:

```
Notes
-----
    This is an example of an indented section. It's like any other section,
    but the body is indented to help it stand out from surrounding text.
    
Examples
--------
    Examples should be written in doctest format, and should illustrate how
    to use the function.

    >>> print([i for i in example_generator(4)])
    [0, 1, 2, 3]
```

Versus in plain reST docstring format, you have to use Sphinx directives which are a different syntax from the `:param [name]: [description]` directives.

```
.. note::
    This is an example of an indented section. It's like any other section,
    but the body is indented to help it stand out from surrounding text.
    
.. rubric:: Example
    >>> print([i for i in example_generator(4)])
    [0, 1, 2, 3]
```

> One thing that may be worth mentioning is that Sphinx can extract parameter types from type annotations and does not require separate type specifications in the docstrings, so, at least as far as this project is concerned (i.e., we require type annotations), the info in https://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html is not entirely accurate/applicable.

The napoleon note that states "Python 2/3 compatible annotations aren’t currently supported by Sphinx and won’t show up in the docs." is referring specifically to the type annotations that look like:
```python
def embezzle(self, account, funds=1000000, *fake_receipts):
    # type: (str, int, *str) -> None
    """Embezzle funds from account using fake receipts."""
    <code goes here>
```

I think it is true that those are not parsed by Sphinx since they are not included in the `docstring`, but either way, as you mention, it doesn't apply to us since we use the python3-only type annotation.

**Comment by jameshcorbett** [comment]
I would vote against reST format also, even though it's what I use because it's what I am familiar with. For a new project I think it makes sense to use one of the other two. And if NumPy is more popular, I would be slightly inclined to go for that one (I also find it a little easier to read), although I agree that constantly typing out "-------" is a pain.

Also, I don't think anyone has mentioned the interactive `help` use-case. If I was a relatively inexperienced user and I saw reST docstrings come up in my terminal, I would be pretty repulsed. Numpy/Google docstrings are non-developer-friendly. For J/PSI I doubt we will see a lot of non-developers exploring our code base, but I do think it is worth considering all the places docstrings come up.

**Comment by hategan** [comment]
@jameshcorbett 
Out of curiosity, what are you editing code with?

The basic idea being that in most cases I'd expect there to be syntax highlighting which makes it easy to spot structure. For example:

```ReST
    :param client: A handle to the :class:`simpleble.SimpleBleClient` client
        object that detected the device
    :param addr: Device MAC address, defaults to None
    :param addrType: Device address type - one of ADDR_TYPE_PUBLIC or
        ADDR_TYPE_RANDOM, defaults to ADDR_TYPE_PUBLIC
    :param iface: Bluetooth interface number (0 = /dev/hci0) used for the
        connection, defaults to 0
    :param data: A list of tuples (adtype, description, value) containing the
        AD type code, human-readable description and value for all available
        advertising data items, defaults to None
    :param rssi: Received Signal Strength Indication for the last received
        broadcast from the device. This is an integer value measured in dB,
        where 0 dB is the maximum (theoretical) signal strength, and more
        negative numbers indicate a weaker signal, defaults to 0
    :param connectable: `True` if the device supports connections, and `False`
        otherwise (typically used for advertising ‘beacons’).,
        defaults to `False`
    :param updateCount: Integer count of the number of advertising packets
        received from the device so far, defaults to 0
    :raises bluepy.btle.BTLEException.GATT_ERROR: If no inputs are specified
        or the requested characteristic was not found.
    :returns: True or False indicating success or failure of write operation, in the
        case that withResponce is True
```

**Comment by hategan** [comment]
> it's what I use because it's what I am familiar with.

We should favor familiarity rather than WP:PERSONAL_PREFERENCE, no?

**Comment by jameshcorbett** [comment]
I use sublime text, and there's no highlighting of parameters like that. (A quick google search suggests that it isn't even available, at least without some effort.) What you show is nice, and makes the reST docstrings much more readable, but I don't think it changes the fact that the numpy/Google strings are more readable to begin with.

> We should favor familiarity rather than WP:PERSONAL_PREFERENCE, no?

I agree familiarity is good. And even though I would prefer Numpy/Google, if you're strongly opposed to them, I would accept reST. It's what I've used and I could live with continuing to use it. But I think the Numpy/Google style is just plain better. And none of them (reST included) are very difficult to learn.

I also don't think it's all that important of a decision, though, because I think all of the options are fine. I just wanted to throw in my vote.

**Comment by hategan** [comment]
> if you're strongly opposed to them

I would really love if you could think not in terms of what you or I want, but in terms of what a random sample of potential contributors would find most comfortable, on average, to work with.

**Comment by SteVwonder** [comment]
On the phone call, we came to consensus that the numpy format is probably the best. So we will move forward with that.
