### ISSUE TITLE
Type Annotations

### ISSUE THREAD

**Issue by jameshcorbett** [ExaWorks/psi-j-python#22]
Since we're talking about [code style](https://github.com/ExaWorks/psi-j-python/issues/20) and [docstring format](https://github.com/ExaWorks/psi-j-python/issues/21), I was wondering if it would be worth discussing type annotations. It sounds like everyone else is intending to annotate everything, which is fine by me, although I wonder if they might be optional until a given project (assuming that the policies put in place in this repo would carry over to Python code in other ExaWorks repos) finds that they would really be beneficial.

**Comment by hategan** [comment]
I think it's detrimental to attempt global policies like this. If we try to make decisions that apply to many projects, it will create a strong incentive to ensure that the "right choice" is made, which can lead to endless discussions.

As far as I'm concerned, I will attempt to annotate the code that I produce. I don't want to go into a long debate about the pros and cons of strong typing or it's attempt to emulate it with mypy in Python, so I'll leave it at that.

**Comment by jameshcorbett** [comment]
Oh, OK. From some of the comments I thought maybe you (or others) were thinking of making type annotations mandatory for contributors.

Even just for this repo, I think it might be good to have a one-sentence policy, saying whether they are optional/recommended/required. I was planning on contributing, and seeing all of the type-annotated code, I probably would have assumed they were required.

**Comment by hategan** [comment]
> making type annotations mandatory for contributors

I'd be inclined to do so. I've seen many cases in which type annotations would have avoided a lot of bug hunting.

**Comment by SteVwonder** [comment]
:+1: I would support a recommendation/requirement for type-annotations.

**Comment by kylechard** [comment]
Seems like we agree here that we should require type-annotations.
