### ISSUE TITLE
How to specify account when running tests

### ISSUE THREAD

**Issue by ketancmaheshwari** [ExaWorks/psi-j-python#233]
I have been trying to make tests on Crusher, a slurm cluster but running into an error that it is missing my slurm Account info. Typically srun takes a command line argument with -A to set Account but I am not sure where psij is supposed to get that info from. As a best guess, I added my account info to `test.conf` as `custom_attributes = "slurm.account": "myaccname" ` and reran make tests but it did not change the outcome. The error message is as follows:

    E           psij.exceptions.SubmitException: sbatch: error: 2 ERRORS FOUND: 
    E           sbatch: error:  
    E           sbatch: error: You must specify an account with the -A flag. Valid accounts are:

Any suggestions how I should tell tests about my slurm Account?

**Comment by hategan** [comment]
Sorry for the delay. What you are doing should work. I  will try to work on figuring out what is going on.

**Comment by hategan** [comment]
Wait, sorry, I didn't carefully read your post.

`make tests` invokes pytest. It does not use `testing.conf`. That's for the automated/ci tests.

You have two options. Run tests directly, like you are doing. Unfortunately, make is funny about processing command line arguments, so you'll have to do it like this:
` PYTHONPATH=${CWD}/src:${CWD}/tests/plugins1:${PWD}/tests/plugins2:${PYTHONPATH} python3 -m pytest -v --custom-attributes='"slurm.account":"myaccname"'`
(pay close attention to the single and double quotes above).

The easier option is to invoke `./psij-ci-run`. That will pick up things in testing.conf.

**Comment by wilke** [comment]
@ketancmaheshwari Did this work for you?

**Comment by ketancmaheshwari** [comment]
Yes, closing.
