### ISSUE TITLE
psij CI setup with cron on Crusher

### ISSUE THREAD

**Issue by ketancmaheshwari** [ExaWorks/psi-j-python#239]
I am trying to setup CI on crusher for psij but seems like nothing is being added to cron. See the transcript below:

`[ketan2@login2.crusher psi-j-python]$ ./psij-ci-setup 

================================================================
This script will install requirements for the PSI/J CI tests and
add a cron job to run the tests once a day at some random time. 
                                                                
If you need to set up a special environment, such as loading an 
environment module please exit this script and add the relevant 
commands to psij-ci-load.                                       
================================================================

Would you like to (C)ontinue or E(x)it? C
Installing dependencies...Done

================================================================
Please choose a method to run the tests:                        
1) Cron  (recommended)
2) AT  
3) Screen  
4) manual  
================================================================
Method 1-4 (1) or E(x)it? 1
================================================================
The following line will be installed in your crontab:
51 17 * * * cd "/autofs/nccs-svm1_home2/ketan2/crusherwork/psi-j-python" && ./psij-ci-run >> testing.log 2>&1
================================================================
no crontab for ketan2
[ketan2@login2.crusher psi-j-python]$ echo $?
0
[ketan2@login2.crusher psi-j-python]$ crontab -l
[ketan2@login2.crusher psi-j-python]$ 
`

I verified separately that cron is supported on crusher. See below:

`
[ketan2@login2.crusher psi-j-python]$ echo '15 18 30 6 * find ~ -mtime +30 -print' > f00

[ketan2@login2.crusher psi-j-python]$ crontab f00 

[ketan2@login2.crusher psi-j-python]$ crontab -l

15 18 30 6 * find ~ -mtime +30 -print

`

Any suggestions as to how to fix this problem?

**Comment by hategan** [comment]
Apparently this happens if you don't have a crontab, which, after testing it with the `echo` job you should. So I suspect that it will work if you try again.

Please lave this issue open since we should also try to find a solution that avoid this problem.

**Comment by hategan** [comment]
PR #245 should fix this issue.
