### ISSUE TITLE
API inconsistent for status callbacks

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/psi-j-python#247]
Setting a status callback on a executor:
```py
def state_cb(job, status):
    print(job.id, str(status)
    
jex = psij.JobExecutor.get_instance(...)
jex.set_job_status_callback(cb)
```

Setting a status callback on a job:
```py
class StateCB(JobStatusCallback):
    def job_status_changed(self, job, status):
        print('Job {}: {}'.format(job.id, status))

job = Job(JobSpec(executable='/bin/date'))
job.status_callback = StateCB()
```

Two questions:
  - 1) should we make this uniform?
  - 2) which way?
  
My opinion:
  - 1) yes
  - 2) use the executor approach also for jobs

**Comment by andre-merzky** [comment]
PS.: it might be good to discuss before release as it affects documented API?

**Comment by hategan** [comment]
Good catch. Clearly, we want uniformity.

I think the only problem I have with the executor approach is that it's somewhat python specific, whereas the other one is a generic OOP solution.

**Comment by andre-merzky** [comment]
> I think the only problem I have with the executor approach is that it's somewhat python specific, whereas the other one is a generic OOP solution.

True - but then again I don't mind python specific for python bindings, really - just the opposite :-)  We could support both - but in general I think it's cleaner to have one way to do things...

Another point in favor for the `callable` approach: I frequently use a class member method as callback, and passing a callable makes this easy.  Coding that via the `JobStatusCallback` route is possible, but quite cumbersome...  But that's just a single data point, just happens to be the one where I stumbled over it...).

**Comment by hategan** [comment]
> > I think the only problem I have with the executor approach is that it's somewhat python specific, whereas the other one is a generic OOP solution.
> 
> True - but then again I don't mind python specific for python bindings, really - just the opposite :-) We could support both - but in general I think it's cleaner to have one way to do things...
> 
> Another point in favor for the `callable` approach: I frequently use a class member method as callback, and passing a callable makes this easy. Coding that via the `JobStatusCallback` route is possible, but quite cumbersome... But that's just a single data point, just happens to be the one where I stumbled over it...).

I think I agree. It seems unlikely that somebody would move from, say, Java to python and be terribly surprised that the callback is a function in python.
