### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/psi-j-python#25]
Local connector tests are failing on Mac.  @hategan is investigating debuggin on AWS

**Comment by hategan** [comment]
Just to clarify why this is taking a while: Mac instances on EC2 require dedicated instances. These are limited to 0, by default, and getting that limit to a non-zero value requires a special request and explanations about the intended usage. This whole process is rather manual, includes multiple levels on the Amazon side, and seems to take some time.
