### ISSUE TITLE
Making working directory for executor configurable through env variable

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psi-j-python#250]
Do we want to set the working directory ~/.psi/work or at least ~/.psij through an environment variable? Right now you have to create an executor and set it in code.

I would change `src/psij/job_executor_config.py:    DEFAULT_WORK_DIRECTORY = Path.home() / '.psij' / 'work'`

**Comment by wilke** [comment]
@hategan any thoughts?

**Comment by hategan** [comment]
I'd keep it simple. If it turns out that there is a need to do it through environment variables, let's consider this issue then.
