### ISSUE TITLE
Check Programming Guide

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psi-j-python#256]
- Proofread automatically generated pages
 - Rename to "contributing to psij" or  "Developer docs" (+2)
 - Test examples and SOPs
 - Update or add content where necessary

**Comment by wilke** [comment]
@hategan Can you add a link to the pages. Are those really autogenerated?

**Comment by jameshcorbett** [comment]
I have gone over the documentation and fixed all the issues I found.

**Comment by mturilli** [comment]
Reached an acceptable state. Open a new ticket if new problems emerge with this.
