### ISSUE TITLE
Landing Page for documentation

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psi-j-python#262]
- Create mock up ; Structure the docs landing page more like dask
- Remove TOC from landing page.
- Use 2 level TOC on left bar and expanders for other levels

Landing Page:
- Less than one page brief intro (with bullet points) with a picture as a must
- Brief code example (not necessarily working code, just showing simple)
- Portability
- Ease of use?
- Reuse and adaption?  

For each documentation task:
1. Author writes draft
2. Team comments/
3. Commit and go to next section

GanttStart: 2022-08-29
GanttDue: 2022-09-23

**Comment by mturilli** [comment]
Add link to Python implementation and make the distinction between spec and implementation at: https://exaworks.org/psij . Make it prominent, maybe an image above the existing image.
