### ISSUE TITLE
Setup test suite at LLNL

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psi-j-python#266]
Setup and document testing on supported machines. Report results automatically to dashboard.

**Comment by wilke** [comment]
@jameshcorbett @mtitov Can you add an update here? Please note problems, modifications or solutions.

**Comment by jameshcorbett** [comment]
I am stuck on the tests for the SDK, which Zeke got to work but I am struggling with.

**Comment by hategan** [comment]
We have lassen, quartz, and ruby, which is a decent set.
