### ISSUE TITLE
log consistency across executors

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/psi-j-python#51]
from @SteVwonder on #26:

> do we want to have some logging consistency across executors for some of the common things like state changes and job submission? If so, we can spin out a separate issue on how to handle this and what logs to do this for.

This is that separate issue.

**Comment by hategan** [comment]
I think, in order to address this, we should start by writing down some requirements.

**Comment by hategan** [comment]
... in other words, consistency means that we have identified a core set of things that need to be logged, or a specific way in which things are to be logged. Absent specifics, I don't see how this could be implemented.

To start with, state changes are logged by the Job class, so there is no need to coordinate across executors. I.e., consistency is automatic.

@andre-merzky, @jameshcorbett, what other things do you think should be there?

**Comment by andre-merzky** [comment]
I propose to close this for the time being - can be reopened once an actual and specific need arises.
