### ISSUE TITLE
Flux executor broken

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/psi-j-python#52]
I am not sure if this is a problem with my local setup, or if the state of the executor deteriorated for some other reason, but I observe this behavior on `main`:
```sh

$ ./tests/run_job.py local
Job submitted
Job done: JobStatus[COMPLETED, time=1629979965.2759883, exit_code=0]

$ ./tests/run_job.py flux
Job submitted
Job done: JobStatus[FAILED, time=1629979974.6525922, meta={'type': 'alloc', 'severity': 0, 'userid': -1, 'note': 'alloc denied due to type="unsatisfiable"', 'exit_code': None, 'message': 'alloc denied due to type="unsatisfiable"'}]
```

I did not yet dig into it, just recording the ticket for now.

PS.: the ticket referred to running the test w/i a flux instance - but that mode is not supported in main yet, there a flux instance is started internally - I edited to reflect that.

**Comment by SteVwonder** [comment]
What are the details of the job being run?  Is it asking for multiple nodes/cores or GPUs?

**Comment by andre-merzky** [comment]
test_run.py is really just running `/bin/date`:
```py
#!/usr/bin/env python3

# This is meant as a simple test file to check if psij was installed successfully

import sys

from psij import Job, JobExecutor, JobSpec


if __name__ == '__main__':
    name = 'local'
    if len(sys.argv) > 1:
        name = sys.argv[1]
    jobs = list()
    job = Job(JobSpec(executable='/bin/date'))
    exec = JobExecutor.get_instance(name)
    exec.submit(job)
    jobs.append(job)
    print('Job submitted')
    status = job.wait()
    print('Job done: {}'.format(status))
```

The generated flux spec is:
```py
{'attributes': {'system': {'duration': 600.0}},
 'resources': [{'count': 1,
                'label': 'task',
                'type': 'slot',
                'with': [{'count': 1, 'type': 'core'},
                         {'count': 1, 'type': 'gpu'}]}],
 'tasks': [{'command': ['/bin/date'],
            'count': {'per_slot': 1},
            'slot': 'task'}],
 'version': 1}
```
I actually don't understand why a GPU is requested, but either way, a GPU is available also.

**Comment by SteVwonder** [comment]
>  The question remains why does the spec fail to run?

That's a good quesiton.  It may be because the Flux instance you are submitting to does not include the flux-sched Fluxion scheduler.  If you run `flux module list` is `sched-simple` loaded?  If so, I believe that is the issue since that scheduler does not support GPUs.  The other issue could be Flux not detecting the GPUs due to an hwloc that isn't configured against CUDA.  Does `flux resource list` report any GPUs?
