### ISSUE TITLE
LSF and Cobalt executors need launchers

### ISSUE THREAD

**Issue by jameshcorbett** [ExaWorks/psi-j-python#58]
In order to launch applications across multiple nodes with various resource requirements.

**Comment by jameshcorbett** [comment]
Cobalt now also needs a launcher thanks to #62

**Comment by hategan** [comment]
#87 adds srun.

I'll add a note, however, that srun does not seem to always be the right choice with Slurm. In particular, mpi applications should still be launched through mpirun.
