### ISSUE TITLE
Remove static access to executors through psij.executors.__init__.py

### ISSUE THREAD

**Issue by hategan** [ExaWorks/psi-j-python#63]
The issue here is executors with dependencies when we would like to guard against import failures due to missing dependencies, such as is the case for the FluxJobExecutor.

We could wrap the import into a try block. However, I don't see how this could be made to work with static type checking. The fundamental problem is that mypy imports modules and checks against the resulting symbols. If the import protection mechanism replaces the `FluxJobExecutor` attribute in `psij.executors.__init__.py` with a mock object, mypy cannot effectively check against the specifics of `FluxJobExecutor`.

We could do something like 6e04d2114acf96b74c975df4e848af0e5c0f76c6, but we run into the same problem within the Flux executor, although with a different manifestation: we can't make mypy happy without hiding the type of the guarded variables.

Even if the executors are not accessible as `psij.executors.<name>`, they remain accessible statically through their canonical names, such as `psij.executors.flux.FluxJobExecutor`, so the consequences are minor.

This is not a problem with the dynamic executor loading scheme since objects returned by the executor factory have the base JobExecutor type.

@andre-merzky, @jameshcorbett: thoughts?

**Comment by jameshcorbett** [comment]
Your points all make sense but they are just persuading me that mypy sucks (I mean it's great and all yadda yadda yadda)

Anyway just removing ``__init__.py`` didn't make a difference for me:

```
(UQP37) ishirini-na-ti:psi-j-python corbett8$ make typecheck
mypy --config-file=.mypy --strict src tests
src/psij/executors/batch/test/qlib.py:9: error: Library stubs not installed for "filelock" (or incompatible with Python 3.7)
src/psij/executors/batch/test/qlib.py:9: note: Hint: "python3 -m pip install types-filelock"
src/psij/executors/batch/test/qlib.py:9: note: (or run "mypy --install-types" to install all missing stub packages)
src/psij/executors/batch/test/qlib.py:9: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/psij/executors/flux.py:32: error: Incompatible types in assignment (expression has type "None", variable has type Module)
Found 2 errors in 2 files (checked 42 source files)
make: *** [Makefile:24: typecheck] Error 1  
(UQP37) ishirini-na-ti:psi-j-python corbett8$ echo "" > src/psij/executors/__init__.py 
(UQP37) ishirini-na-ti:psi-j-python corbett8$ make typecheck
mypy --config-file=.mypy --strict src tests
src/psij/executors/batch/test/qlib.py:9: error: Library stubs not installed for "filelock" (or incompatible with Python 3.7)
src/psij/executors/batch/test/qlib.py:9: note: Hint: "python3 -m pip install types-filelock"
src/psij/executors/batch/test/qlib.py:9: note: (or run "mypy --install-types" to install all missing stub packages)
src/psij/executors/batch/test/qlib.py:9: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/psij/executors/flux.py:32: error: Incompatible types in assignment (expression has type "None", variable has type Module)
Found 2 errors in 2 files (checked 42 source files)
make: *** [Makefile:24: typecheck] Error 1
```

**Comment by hategan** [comment]
#104 removes explicit access to anything but core executors with no dependencies from psij.executors(.__init__.py), which addresses the initial issue.
