### ISSUE TITLE
Templating engine woes

### ISSUE THREAD

**Issue by jameshcorbett** [ExaWorks/psi-j-python#68]
Our templating engine, [pystache](https://github.com/defunkt/pystache), is causing us some trouble. It breaks our readthedocs builds and other things (more [here](https://github.com/ExaWorks/psi-j-python/pull/55#issuecomment-955772766)). The way it fails is configuration-dependent but it manages to fail in interesting ways no matter what. 

@hategan mentioned a few options we have:

> There is a promising fork of pystache whose maintainer is attempting to take over the pypi package (see pypa/pypi-support#1422). We could point to that github repo until the issue gets sorted.
> 
> There is also a newer implementation of mustache, https://github.com/noahmorrison/chevron, but it seems less used/tested. However, if the situation above does not resolve in a timely manner, this may end up being the better solution.

I wonder though if we might consider using [jinja](https://github.com/pallets/jinja) instead?

**Comment by hategan** [comment]
> I wonder though if we might consider using [jinja](https://github.com/pallets/jinja) instead?

We want a cross-language engine and it seems like an implementation of mustache is the only available choice.

**Comment by hategan** [comment]
I can fork an updated version, tag, and we can use that until we either move to a different implementation, different engine, or the one currently on pypi gets fixed. Does that sound reasonable?

**Comment by jameshcorbett** [comment]
If you want to take on the responsibility yourself, whatever you want to do to get things working is fine by me. I just want things to work, and I would love to get the readthedocs build to pass so our CI will actually turn green.

Our mustache options don't seem great to me at first glance, although they might turn out well upon testing. We could always just try out chevron or the new pystache and see how it goes, and whether the developers are responsive, and then decide if we want to use one of them.

I'm not convinced that we should really care that much about a cross-language solution. We're not using our templating libraries for anything very complicated so it's generally a pretty straightforward translation from one templating library to another (are the delimiters ``{%`` or ``{{`` or ``%%``?). My guess is that re-writing the templating stuff would be like 5% of the work of a new PSI/J language implementation.

But mustache is what we have now and I like your plan.

**Comment by hategan** [comment]
> I'm not convinced that we should really care that much about a cross-language solution. We're not using our templating libraries for anything very complicated so it's generally a pretty straightforward translation from one templating library to another

It's an unnecessary step for users on a system that needs customized templates to have to do so for every language implementation and test such copy separately. We may never really get to that point, but, if we do, I'd rather not be in that situation because of a temporary snag with a library. It may be useful to recognize that we cannot, in general, guarantee that any of our dependencies will always be nice and dandy.

**Comment by hategan** [comment]
A recent version of pystache is now available and PR #100 switches to it.

**Comment by hategan** [comment]
#100 was merged into main, so this should be fixed now.
